### PR TITLE
Upgrade to RxJava 2.2.1, fixes due to internal changes in Rx

### PR DESCRIPTION
**Pull request by akarnokd**
This PR upgrades the library to RxJava 2.2.1 and updates the code that depended on internal components, which have been changed in RxJava 2.2.1, making the release version of this library incompatible with 2.2.1.

### CODE REVIEW

**Comment by TonyTangAndroid** [comment]
Might I ask how soon this pull request will be merged?

**Comment by ezet** [comment]
I'm wondering the same.

**Comment by akarnokd** [comment]
I'm not sure what the holdup is. Based on the [Github activity](https://github.com/akaita), the owner is quite productive outside this project.

**Comment by skykelsey** [comment]
@akaita Do you have time to merge this and create a release? 🙏

**Comment by akaita** [comment]
Published in 1.3.0.
It's already available in jcenter. Waiting for maven to distribute it (anything between 10 minutes and 2 hours).
Closes #11

**Pull request merged**
